### ISSUE TITLE
Need access to exception causing failure.

### ISSUE THREAD

**Issue by ataylor284** [elennick/retry4j#27]
It would be useful if the exception that caused the retry was somehow available in the AfterFailedTryListener.  In particular, logging the exception from this handler is probably a common pattern.

A possible solution would be to populate a new field containing the last seen exception on the CallResults object.

**Comment by elennick** [comment]
@ataylor284 seems like a good idea, will add as an enhancement

**Comment by elennick** [comment]
@ataylor284 fyi i just merged your pull requests... if you're interested in addressing this issue as well let me know

**Comment by ataylor284** [comment]
Sure, I'll write up a patch.

**Comment by elennick** [comment]
@ataylor284 I actually just pushed an 0.6.1 release with a small change to include the exception that caused the retry in the listener... it actually turned out i ran into the same problem as you and really needed access to it while utilizing the library. That being said, I did it very quick and dirty so if you are still interested in doing a more proper implementation just let me know and I will leave this issue open for you.

**Comment by ataylor284** [comment]
Looks pretty close to what I had in mind.  Thanks for adding the enhancement!

**Comment by elennick** [comment]
@ataylor284 Just fyi, i just pushed another release, 0.6.2 where i moved the last thrown exception into the ```CallResults``` object instead of as a parameter of the ```AfterFailedRetryListener```... this way it is available in all listeners (or not populated if not relevant)... this way even if you are using the ```onFailure()``` listener or catching ```RetriesExhaustedException```'s, you'll still get the last encountered exception.

Anyhow, you should just be able to say ```result.getLastExceptionThatCausedRetry()``` from any listener now to get the last exception (if there is one, otherwise it will be null)
