### ISSUE TITLE
RetriesExhaustedException has no cause

### ISSUE THREAD

**Issue by mkopylec** [elennick/retry4j#41]
I think the `RetriesExhaustedException` should have a cause exception which is the `lastExceptionThatCausedRetry`. Often applications just log exception stack traces and do nothing more. When the exception has no cause there is no information what happened.
What do you think?

**Comment by elennick** [comment]
it is technically possible that different exceptions could cause retries within the same execution which makes only giving information about the last one feel kind of weird... maybe it'd make more sense to provide a list of exceptions instead of just the last one in case there is more than one... let me think about it and see what makes sense

**Comment by mkopylec** [comment]
I know the possibility but a stack trace without a cause is useless in my opinion.
Retrieving all tries exceptions would also be a useful enhancement but that's another story :)

**Comment by elennick** [comment]
closed with 0.7.3 release just now

**Comment by mkopylec** [comment]
Great!
